export enum AuthActionTypes {
    FETCH_USERDATA_SUCCESS = "FETCH_USERDATA_SUCCESS",
    FETCH_USERDATA_ERROR = "FETCH_USERDATA_ERROR",
    LOGOUT = "LOGOUT",
    REGISTRATION_SUCCESS = "REGESTRATION_SUCCESS",
    REGISTRATION_ERROR = "REGISTRATION_ERROR"
}

export enum ProductsActionTypes {
    FETCH_PRODUCTS = "FETCH_PRODUCTS",
    FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS",
    FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS"
}

export const FETCH_PRODUCTS: string = "FETCH_PRODUCTS";
